
version: 2

models:
  - name: films
    description: "This table contains all the films details."
    columns:
      - name: film_id
        description: "The primary key for this table."
        data_tests:
          - unique
          - not_null
      
      - name: title
        description: "The title of the film."
        data_tests:
          - not_null

      - name: release_date
        description: "The release year of the film."
        data_tests:
          - not_null
          
      - name: price
        description: "The price of the film."
        data_tests:
          - not_null
          
      - name: rating
        description: "The rating of the film."
        data_tests:
          - not_null
          
      - name: user_rating
        description: "The rating of the film by users."
        data_tests:
          - not_null


  - name: actors
    description: "This table contains all the actors details."
    columns:
      - name: actor_id
        description: "The primary key for this table."
        data_tests:
          - unique
          - not_null

      - name: name
        description: "The first name of the actor."
        data_tests:
          - not_null


  - name: film_actors
    description: "This table contains all the film_actors details."
    columns:
      - name: film_id
        description: "The primary key for this table."
        data_tests:
          - unique
          - not_null

      - name: actor_id
        description: "The primary key for this table."
        data_tests:
          - unique
          - not_null


  - name: film_ratings
    description: "This table contains all the film_ratings details."
    columns:
      - name: film_id
        description: "The primary key for this table."
        data_tests:
          - unique
          - not_null

      - name: title
        description: "The title of the film."
        data_tests:
          - not_null

      - name: release_date
        description: "The release year of the film."
        data_tests:
          - not_null

      - name: price
        description: "The price of the film."
        data_tests:
          - not_null

      - name: rating
        description: "The rating of the film."
        data_tests:
          - not_null

      - name: user_rating
        description: "The rating of the film by users."
        data_tests:
          - not_null

      - name: actor_count
        description: "The number of actors in the film."
        data_tests:
          - not_null

      - name: avg_rating
        description: "The average rating of the film."
        data_tests:
          - not_null
    